import Foundation
import SwiftUI

struct Story: Identifiable, Codable {
    var id: String { title }
    let title: String
    let content: String
    var category: String = "General"
    var readTime: Int = 3
}

@MainActor
public class StoryManager: ObservableObject {
    public static let shared = StoryManager()
    @AppStorage("likedStoryIDs") private var likedStoryIDsRaw: String = ""

    var likedStoryIDs: [String] {
        get { likedStoryIDsRaw.split(separator: ",").map(String.init) }
        set { likedStoryIDsRaw = newValue.joined(separator: ",") }
    }

    func isLiked(story: Story) -> Bool { likedStoryIDs.contains(story.id) }

    func toggleLike(for story: Story) {
        var current = likedStoryIDs
        if let index = current.firstIndex(of: story.id) {
            current.remove(at: index)
        } else {
            current.append(story.id)
        }
        likedStoryIDs = current
    }

    // MARK: - Public API (language-aware)

    func getStory(for mood: Mood) -> Story {
        getStories(for: mood).randomElement()
            ?? Story(title: L10n.t(.appName), content: "Hello dear, I'm so happy to see you!", category: "General", readTime: 1)
    }

    func getStory(id: String) -> Story? {
        for mood in Mood.allMoods {
            if let story = getStories(for: mood).first(where: { $0.id == id }) { return story }
        }
        return nil
    }

    func getStories(for mood: Mood) -> [Story] {
        let lang = LanguageManager.shared.selectedLanguage
        return localizedStories(mood: mood.name, language: lang)
    }

    func getRandomStory(for mood: Mood) -> Story {
        let base = getStories(for: mood).randomElement() ?? getStory(for: mood)
        let extras = [
            "\n\nAnd remember, my dear, every sunset promises a new sunrise.",
            "\n\nNow come, let me make you a warm cup of tea while we sit together.",
            "\n\nYou know, your grandfather would have loved to hear this story too.",
            "\n\nSometimes the best stories are the ones we live, not just the ones we hear.",
            "\n\nNow, shall I tell you another? Or shall we just sit here and enjoy the quiet together?"
        ]
        return Story(title: base.title, content: base.content + extras.randomElement()!, category: base.category, readTime: base.readTime)
    }

    func getAllStories() -> [Story] {
        Mood.allMoods.flatMap { getStories(for: $0) }
    }

    // MARK: - Language routing

    private func localizedStories(mood: String, language: AppLanguage) -> [Story] {
        switch language {
        case .mandarin: return mandarinStories[mood] ?? englishStories[mood] ?? []
        case .hindi:    return hindiStories[mood] ?? englishStories[mood] ?? []
        case .spanish:  return spanishStories[mood] ?? englishStories[mood] ?? []
        case .french:   return frenchStories[mood] ?? englishStories[mood] ?? []
        case .english:  return englishStories[mood] ?? []
        }
    }

    // MARK: - English Stories

    private lazy var englishStories: [String: [Story]] = [
        "Happy": [
            Story(title: "The Garden of Joy", content: "Oh, hello my dear! It brings such warmth to my heart to see you smiling. You know, happiness is like my old garden in the springtime. I would spend hours on my hands and knees, pulling weeds and planting tiny, unassuming seeds. Sometimes I'd wonder if anything would ever grow. But then, one bright morning, the whole yard would explode in color—yellow daffodils, soft pink roses, and bright red tulips swaying in the breeze. That is what joy feels like. It is the sudden bloom of all the good things you have been quietly cultivating inside yourself. Let yourself soak in that sunshine today. You have earned every petal of it.", category: "Nature", readTime: 3),
            Story(title: "The Surprise Picnic", content: "Do you remember the time we went on a picnic and realized we left the entire basket on the kitchen counter? Oh, we laughed so hard until our bellies literally hurt! We ended up eating wild blackberries we found near the trail and telling silly jokes under the shade of that massive old oak tree. It wasn't the fancy lunch we planned, but it was absolutely perfect because we were together. Sometimes the greatest joy doesn't come from a perfect plan, but from the spontaneous, messy moments we share with people we love.", category: "Funny", readTime: 2),
            Story(title: "The Dancing Fireflies", content: "When I was a little girl, the summer nights were thick with heat and filled with fireflies. They danced across the tall grass like tiny fallen stars blinking their silent, golden songs. We would run until our legs were tired, catching them gently in our cupped hands just to see them glow against our palms, make a quick wish, and let them fly up into the dark sky. Your wonderful smile right now reminds me of that exact same light—pure, magical, and full of endless hope.", category: "Bedtime", readTime: 4)
        ],
        "Sad": [
            Story(title: "The Rainy Window", content: "Come here, sweet child. Let me wrap this warm, heavy blanket around your shoulders. I can see a grey cloud hanging over you today. Listen to the rain softly tapping against the glass. Even the sky needs to cry sometimes, didn't you know? The earth needs that rain to wash away the dust and to help the deep roots drink. Your tears are doing the exact same thing. They are watering your soul and washing away the heavy things you've been carrying. It's perfectly alright to sit here in the quiet with me until the sun decides to peek through the clouds again.", category: "Comfort", readTime: 3),
            Story(title: "The Broken Teacup", content: "I once had a delicate, beautiful porcelain teacup that slipped from my hands and shattered into a dozen pieces. I felt so devastated. But your grandfather didn't throw it away. He helped me glue it carefully back together, and he painted the cracked lines with brilliant gold lacquer. He told me, 'Now it's even more beautiful because it has a history. It survived being broken.' You might feel broken right now, my love. But those cracks are where your golden strength lives. You are so much stronger and more beautiful because of everything you have survived.", category: "Moral", readTime: 3),
            Story(title: "The Moon's Hiding Place", content: "Did you know that even the great, shining moon disappears sometimes? She gets completely hidden by the dark night sky. But she never actually leaves us. She is simply resting, gathering her silvery light quietly in the shadows so she can return and shine even brighter. It is perfectly okay to hide for a little while when you feel sad, my love. You don't always have to be glowing for the rest of the world. Just rest. Your light is safe, and it will return when you are ready.", category: "Bedtime", readTime: 2)
        ],
        "Anxious": [
            Story(title: "The Ancient Oak", content: "Breathe with me, deep and slow. In through your nose, out through your mouth. Imagine a vast, quiet forest, and right in the center is an ancient, massive oak tree. The wind is howling, and the branches are furiously whipping back and forth in a fierce storm. But under the earth, those roots are wrapped tightly around solid rock. The tree does not panic; it just holds on and lets the storm pass over it. Your anxiety is just weather, my brave one. You are the tree. Send your roots down deep. The storm will exhaust itself and pass, but you will still be standing.", category: "Nature", readTime: 3),
            Story(title: "The River's Flow", content: "Ideally, life is meant to flow like a beautiful, continuous river. Sometimes that river rushes violently over sharp rocks, and sometimes it meanders calmly through green meadows. But the water never worries about where it's going—it simply trusts that the path will eventually lead it to the vast, peaceful ocean. You are trying to control the water right now, and it is exhausting you. Trust your path, my dear. You will get to exactly where you need to be. Let go of the oars for a moment and just let the current carry you.", category: "Moral", readTime: 3),
            Story(title: "Grandma's Secret Pocket", content: "I used to carry a very smooth, polished river stone deep in my apron pocket whenever I felt scared or nervous. Whenever my heart would start racing, I'd trace the smooth edges with my thumb and quietly remind myself: 'This too shall pass. I am safe.' Imagine I am placing that very same warm stone into the palm of your hand right now. Close your fingers around it. Feel its weight. Whenever your mind races today, gently squeeze your hand and know that Grandma is right here with you.", category: "Comfort", readTime: 2)
        ],
        "Lonely": [
            Story(title: "The Symphony of Stars", content: "Oh, my precious one. Loneliness can feel so frightfully cold and vast. But I want you to step outside tonight and look up at the dark sky. Do you see all those millions of stars? Each one is sitting alone in the freezing darkness of space, separated by millions of miles. And yet, together, they create the most breathtaking, sparkling blanket that comforts the entire world. We are all under that exact same sky. You might feel like a single star right now, but you are part of a beautiful, connected constellation. You are never truly alone.", category: "Bedtime", readTime: 4),
            Story(title: "The Invisible Thread", content: "There is an old, ancient legend that says an invisible red thread connects those who are destined to love and support each other. It can stretch across oceans and stretch through years of time, but it never, ever breaks. Even when you are sitting in a quiet, empty room and the silence feels heavy, that thread is tied firmly around your heart, connecting you right to mine, and to the hearts of people you haven't even met yet. Give it a little tug in your mind, and know that I am tugging back.", category: "Moral", readTime: 3),
            Story(title: "The Letter in the Mail", content: "When I was a young woman living alone in a new city, I used to feel incredibly lonely. The mailboxes were always empty. So, I started writing kind letters to myself. I would tell myself all the wonderful things I desperately needed to hear: 'You are kind, you are smart, you are deeply worthy of love.' And when they arrived in the mail days later, it felt like a hug from a dear friend. Maybe today, you can be your own best friend, too. Write yourself a note of love. You deserve to hear it.", category: "Comfort", readTime: 2)
        ],
        "Tired": [
            Story(title: "The Cozy Quilt", content: "Oh my dear, you look so very weary. Your shoulders are drooping and your eyes are heavy. Let me tell you about the thick patchwork quilt my mother hand-made for me when I was a child. It was heavy, soft, and smelled faintly of lavender and old cedar. Whenever the world demanded too much of me, I would crawl under that heavy quilt, and the weight of the fabric made the weight of the world disappear. Imagine me tucking that quilt securely around you right now. Close your eyes. You don't have to carry anything today. Just rest.", category: "Comfort", readTime: 3),
            Story(title: "The Hibernating Bear", content: "Think of the great grizzly bears up in the snowy mountains. They sleep all winter long, completely still, letting the snow pile high outside their dens. They don't apologize for resting; they don't feel guilty for not being out foraging. They know deep in their bones that immense rest is exactly how they survive. You are allowed to hibernate, my sweet love. Rest is not a weakness; it is the ultimate act of gathering your strength. Let out a big yawn and simply close your eyes.", category: "Bedtime", readTime: 2),
            Story(title: "The Cat on the Windowsill", content: "Have you ever just sat quietly and watched a house cat sleep in a warm puddle of sunshine? They are the purest masters of rest. They stretch their front paws out, they yawn widely, and they do not have a single worry about the chores or the emails waiting for them. Channel your inner cat today. Find a warm, quiet spot in your house, curl up, and just... be. The world will still be there when you wake up, I promise.", category: "Funny", readTime: 2)
        ],
        "Angry": [
            Story(title: "The Thunderstorm", content: "I see the fierce fire in your eyes, and your jaw is set so tight. Anger is exactly like a wild, sudden thunderstorm. It rumbles loudly in your chest, lightning flashes in your mind, and it demands to be felt. It is terrifying, but it is also completely natural. You do not need to fight the storm. Let the thunder roll and the heavy rain fall. But always remember, a storm eventually runs out of rain. And when it passes, it leaves the air smelling fresh, and the ground washed clean. Let the anger wash through you and leave you clean.", category: "Nature", readTime: 3),
            Story(title: "The Hot Coal", content: "When I was younger, my temper was quick. Someone told me once that holding onto bitter anger is exactly like grasping a burning hot coal with the intent of throwing it at someone else. Who is the one getting burned? Only you. Your hands, your heart, your peace of mind. I know you feel justified, and perhaps you are! But drop the coal, my dear. Let it fall to the dirt. Step away and let your own hands heal. You deserve peace much more than you deserve to be 'right'.", category: "Moral", readTime: 2),
            Story(title: "The Scribble Page", content: "Whenever I was boiling mad and the words wouldn't come out right, I would take a big black crayon and scribble as hard and as violently as I could on a scratch piece of paper. Round and round, pressing so hard the wax would snap! I'd draw sharp lines and chaotic circles. And you know what? It felt wonderfully exhausting. It is so much better to let that fierce energy out on a piece of paper instead of letting it burn up inside you or hurt the people around you. Try it sometime! Get the angriest crayon you have.", category: "Funny", readTime: 2)
        ],
        "Grateful": [
            Story(title: "The Thank You Jar", content: "Oh, what a wonderfully warm, expansive feeling gratitude is! It makes your chest feel light. Let me tell you about my old glass Thank You Jar. Every evening, I would take a tiny scrap of paper and write down just one incredibly small thing I was thankful for. Not the big things like a promotion or a new house, but things like 'a perfectly ripe peach' or 'the smell of rain on hot pavement.' After a year, the jar was overflowing. When you train your eyes to look for tiny miracles, you suddenly realize they are scattered everywhere around you.", category: "Moral", readTime: 3),
            Story(title: "The Golden Spectacles", content: "Imagine for a moment if I handed you a pair of antique, magical golden glasses. The moment you slip them onto your face, everything you love starts to glow with a soft, warm, radiant light. The coffee mug in your hand glows. The faithful dog at your feet glows. The sunshine coming through the window glows brightly. Gratitude is simply putting on those invisible golden glasses. You suddenly stop seeing what is missing, and you are surrounded by the blinding beauty of everything you already have.", category: "Bedtime", readTime: 3),
            Story(title: "The Gift of Today", content: "There is an old saying that I've always held close to my heart: Yesterday is history, tomorrow is a total mystery, but today is an absolute gift. That is precisely why it is called the 'present'! You are unwrapping today right now. Whatever it holds, whatever challenges or simple joys, it is yours to live. I am so deeply grateful for the precious gift of you, sitting right here, sharing this exact moment with me.", category: "Short", readTime: 1)
        ],
        "Excited": [
            Story(title: "The Ticket to Anywhere", content: "Oh, I can see the absolutely electric sparkle in your eyes! You remind me of the day I found a train ticket tucked inside an old birthday card. It was a ticket to anywhere I wanted to go. Do you know that fluttering, slightly nervous, wonderfully light feeling in your stomach? That is the feeling of sheer, boundless possibility. Run with it, my adventurous one! Let that excitement carry you like a strong wind. The world is vast and waiting just for you to step out the door.", category: "Short", readTime: 3),
            Story(title: "The First Snowfall", content: "Do you remember the unparalleled magic of waking up as a small child, rushing to the window, and seeing the entire world turned pristine, sparkling white? The dirt and the roads were covered in a thick blanket of quiet snow. The urge to immediately run outside, be the very first person to make footprints, to catch a frozen snowflake on your tongue—that is pure, unadulterated excitement. Hold onto that child-like wonder tightly. Let yourself be thrilled by the newness of things!", category: "Nature", readTime: 2),
            Story(title: "The Bakery Smell", content: "There is absolutely nothing like walking past a small neighborhood bakery early in the morning. The rich, buttery smell of yeast and warm sugar floats out the door and wraps around you. The sheer anticipation of stepping inside and waiting for that very first, hot, flaky bite is intoxicating! Life, my dear, is full of sweet, delicious moments waiting just around the corner, waiting for you to taste them. Savor this lively anticipation!", category: "Funny", readTime: 2)
        ]
    ]

    // MARK: - Hindi Stories (हिन्दी कहानियाँ)

    private lazy var hindiStories: [String: [Story]] = [
        "Happy": [
            Story(title: "खुशी का बगीचा", content: "अरे, मेरे प्यारे! तुम्हें मुस्कुराते देखकर मेरा दिल खिल उठता है। खुशी वैसी ही होती है जैसे बसंत में मेरा पुराना बगीचा। मैं घुटनों के बल बैठकर घास उखाड़ती और छोटे-छोटे बीज बोती थी। कभी-कभी सोचती — क्या कुछ उगेगा भी? लेकिन फिर एक सुबह, पूरा आँगन पीले गेंदों, गुलाबी गुलाबों और लाल ट्यूलिप से भर जाता था। यही तो खुशी है — उन सारी अच्छी चीज़ों का अचानक खिल जाना जो तुम अपने अंदर चुपचाप पाल रहे थे। आज उस धूप में भीगो। तुमने हर पंखुड़ी कमाई है।", category: "Nature", readTime: 3),
            Story(title: "अचानक की पिकनिक", content: "याद है जब हम पिकनिक पर गए और घर पर टोकरी भूल आए? हम हँसते-हँसते लोट-पोट हो गए थे! रास्ते में जंगली जामुन खाए और उस बड़े-से पेड़ की छाँव में मज़ेदार किस्से सुनाए। जो खाना था वो नहीं था, पर वो पल परफेक्ट था — क्योंकि हम साथ थे। असली खुशी किसी योजना में नहीं, बल्कि उन अनायास और लापरवाह लमहों में होती है जो हम अपने प्यारों के साथ बिताते हैं।", category: "Funny", readTime: 2),
            Story(title: "टिमटिमाते जुगनू", content: "बचपन में गर्मियों की रातें जुगनुओं से भरी होती थीं। वे लंबी घास पर छोटे-छोटे टूटे तारों की तरह नाचते थे। हम दौड़ते, उन्हें हथेलियों में बंद करते, एक इच्छा माँगते और फिर आसमान में उड़ा देते। तुम्हारी मुस्कान अभी ठीक उसी रोशनी जैसी है — शुद्ध, जादुई और अनंत उम्मीद से भरी।", category: "Bedtime", readTime: 4)
        ],
        "Sad": [
            Story(title: "बारिश भरी खिड़की", content: "आओ मेरे पास, प्यारे बच्चे। तुम्हारे कंधों पर यह गर्म कंबल डाल दूँ। आज तुम पर उदासी का बादल मँडरा रहा है। सुनो — बारिश कैसे शीशे पर थपकी दे रही है। कभी-कभी आसमान को भी रोना पड़ता है। धरती को उस पानी की ज़रूरत होती है — धूल धोने के लिए, जड़ों को तृप्त करने के लिए। तुम्हारे आँसू भी ऐसे ही हैं। वे तुम्हारी आत्मा को सींचते हैं। यहाँ मेरे पास बैठो। जब सूरज निकलेगा, तब निकलेगा।", category: "Comfort", readTime: 3),
            Story(title: "टूटा हुआ प्याला", content: "एक बार मेरे हाथ से एक नाज़ुक चीनी मिट्टी का प्याला गिर गया और टूट गया। मैं बहुत दुखी हुई। लेकिन दादाजी ने उसे फेंका नहीं। उन्होंने उसे जोड़ा और टूटी हुई जगहों पर सुनहरा लाख लगाया। बोले, 'अब यह और सुंदर है क्योंकि इसकी एक कहानी है।' तुम अभी टूटा हुआ महसूस कर रहे हो — लेकिन वही दरारें तुम्हारी सोने जैसी ताकत दिखाती हैं।", category: "Moral", readTime: 3),
            Story(title: "चाँद की छुपने की जगह", content: "जानते हो, चाँद भी कभी-कभी गायब हो जाता है। अंधेरी रात उसे ढक लेती है। लेकिन वो जाता नहीं — बस आराम करता है, ताकि फिर और चमकदार होकर आए। जब मन उदास हो, तुम भी छुप सकते हो थोड़ी देर। हर वक्त चमकते रहना ज़रूरी नहीं। बस आराम करो — तुम्हारी रोशनी वापस आएगी।", category: "Bedtime", readTime: 2)
        ],
        "Anxious": [
            Story(title: "पुराना बरगद", content: "मेरे साथ साँस लो — नाक से अंदर, मुँह से बाहर। कल्पना करो एक घने जंगल के बीच एक विशाल बरगद है। आँधी चल रही है, डालियाँ झूल रही हैं। लेकिन ज़मीन के नीचे उसकी जड़ें पत्थरों को थामे हैं। पेड़ घबराता नहीं — बस टिका रहता है। तुम्हारी चिंता भी बस एक मौसम है। तुम वो पेड़ हो। अपनी जड़ें गहरी उतारो। तूफान थक जाएगा — तुम खड़े रहोगे।", category: "Nature", readTime: 3),
            Story(title: "नदी का बहाव", content: "ज़िंदगी नदी की तरह बहती है। कभी पत्थरों से टकराती है, कभी मैदानों में शांत हो जाती है। पर पानी कभी नहीं पूछता — मुझे कहाँ जाना है? वो बस बहता रहता है, जानता है कि रास्ता मिल ही जाएगा। तुम पानी को रोकने की कोशिश कर रहे हो — यही थका देता है। जाने दो। तुम वहाँ पहुँचोगे जहाँ तुम्हें होना चाहिए।", category: "Moral", readTime: 3),
            Story(title: "दादी की जेब का पत्थर", content: "जब मैं डरती थी, मेरे apron की जेब में एक चिकना-सा पत्थर होता था। जब दिल तेज़ धड़कता, मैं उसे अँगूठे से सहलाती और कहती — 'यह भी गुज़र जाएगा। मैं सुरक्षित हूँ।' अभी कल्पना करो मैं वही पत्थर तुम्हारी हथेली में रख रही हूँ। उसे पकड़ो। उसका भार महसूस करो। जब मन भागे — बस इसे थामो। दादी यहाँ है।", category: "Comfort", readTime: 2)
        ],
        "Lonely": [
            Story(title: "तारों की सिम्फनी", content: "मेरे प्यारे, अकेलापन बहुत ठंडा और विशाल लगता है। लेकिन आज रात बाहर जाओ और आसमान देखो। लाखों तारे हैं — हर एक करोड़ों मील दूर, अकेला। फिर भी मिलकर वे एक ऐसी चादर बनाते हैं जो पूरी दुनिया को सहलाती है। हम सब उसी आसमान के नीचे हैं। तुम भले अभी अकेले तारे लगो — पर तुम एक पूरे तारामंडल का हिस्सा हो। कभी सच में अकेले नहीं।", category: "Bedtime", readTime: 4),
            Story(title: "अदृश्य धागा", content: "एक पुरानी कहानी है — एक लाल धागा उन लोगों को बाँधता है जो एक-दूसरे से प्यार करने के लिए बने हैं। वो धागा समुद्र पार करता है, सालों से नहीं टूटता। अभी जब कमरा सुनसान लगे और चुप्पी भारी हो — वो धागा तुम्हारे दिल से मेरे दिल तक बँधा है। ज़रा खींचो — मैं भी खींच रही हूँ।", category: "Moral", readTime: 3),
            Story(title: "डाक में पत्र", content: "जब मैं किसी नए शहर में अकेली रहती थी, लेटरबॉक्स खाली होता था। तो मैंने खुद को पत्र लिखने शुरू किए। अपने आप से कहती — 'तुम दयालु हो, बुद्धिमान हो, प्यार के लायक हो।' जब वो पत्र आते, लगता जैसे किसी दोस्त ने गले लगाया हो। आज तुम भी खुद के सबसे अच्छे दोस्त बनो। खुद को एक प्यार का नोट लिखो। तुम इसके हकदार हो।", category: "Comfort", readTime: 2)
        ],
        "Tired": [
            Story(title: "आरामदेह रजाई", content: "मेरे प्यारे, तुम बहुत थके नज़र आ रहे हो। मेरी माँ ने जो रजाई बनाई थी — वो भारी, मुलायम थी, लैवेंडर और पुराने देवदार की खुशबू से महकती थी। जब दुनिया बहुत माँगने लगती, मैं उसके नीचे दुबक जाती और दुनिया का बोझ हल्का हो जाता। कल्पना करो मैं अभी वो रजाई तुम पर ओढ़ा रही हूँ। आँखें बंद करो। आज कुछ उठाने की ज़रूरत नहीं। बस आराम करो।", category: "Comfort", readTime: 3),
            Story(title: "हाइबरनेट करता भालू", content: "पहाड़ों के भालुओं की सोचो — वे सारी जाड़े में सोते हैं। माफी नहीं माँगते। जानते हैं कि यही ताकत जमा करने का तरीका है। तुम भी हाइबरनेट कर सकते हो। आराम कमज़ोरी नहीं, बल्कि ताकत जुटाने की कला है। एक बड़ी उबासी लो और बस... सो जाओ।", category: "Bedtime", readTime: 2),
            Story(title: "खिड़की पर बिल्ली", content: "कभी देखा एक बिल्ली धूप में कैसे सोती है? बेफिक्र, बिना किसी चिंता के। आज उस बिल्ली जैसे बनो। घर में कोई गरम कोना ढूँढो, लेट जाओ बस। दुनिया तुम्हारा इंतज़ार करेगी। वादा।", category: "Funny", readTime: 2)
        ],
        "Angry": [
            Story(title: "आँधी-तूफान", content: "मैं तुम्हारी आँखों में आग देख रही हूँ। गुस्सा एक अचानक आए तूफान जैसा होता है — गरजता है, बिजली चमकती है। डरावना है, पर स्वाभाविक भी। तूफान से लड़ो मत। बस उसे गुज़रने दो। तूफान आखिरकार थक जाता है — और पीछे ताज़ी हवा और धुली धरती छोड़ जाता है। गुस्से को भी बहने दो — और शांत हो जाने दो।", category: "Nature", readTime: 3),
            Story(title: "जलता कोयला", content: "जब मैं छोटी थी, मेरा गुस्सा जल्दी उठता था। किसी ने कहा — गुस्से को पकड़े रहना ऐसा है जैसे जलता कोयला किसी पर फेंकने के लिए हाथ में थामे रहो। जलता कौन है? बस तुम। अपने हाथ छोड़ दो। कोयला गिराओ। अपने आप को शांति देने का हक है — यह सही-गलत से ज़्यादा ज़रूरी है।", category: "Moral", readTime: 2),
            Story(title: "काले क्रेयॉन की लकीरें", content: "जब मुझे बहुत गुस्सा आता था, मैं एक काले क्रेयॉन से कागज़ पर जोर-जोर से लकीरें खींचती थी। गोल-गोल, तेज़-तेज़! और जानते हो क्या हुआ? अच्छा लगा। उस ऊर्जा को कागज़ पर निकालना किसी को चोट पहुँचाने से कहीं बेहतर है। कभी कोशिश करो — सबसे गुस्से वाला क्रेयॉन उठाओ!", category: "Funny", readTime: 2)
        ],
        "Grateful": [
            Story(title: "शुक्रिया का डिब्बा", content: "कृतज्ञता कितनी गर्म और विशाल भावना है! मेरे पास एक पुराना शीशे का डिब्बा था — हर शाम मैं एक छोटी-सी चीज़ का शुक्रिया लिखती थी। बड़ी तरक्की नहीं — बस 'पका हुआ आम' या 'बारिश के बाद की खुशबू।' एक साल में डिब्बा भर गया। जब तुम छोटे-छोटे चमत्कारों को देखने की आदत डालते हो, वे हर जगह मिलते हैं।", category: "Moral", readTime: 3),
            Story(title: "सुनहरे चश्मे", content: "सोचो अगर मैं तुम्हें एक जादुई सुनहरा चश्मा दूँ। उसे पहनते ही — जो भी चीज़ तुमसे प्यार करती है, वो चमकने लगती है। हाथ में चाय का कप, पाँव में बैठा कुत्ता, खिड़की से आती धूप — सब चमकते हैं। कृतज्ञता वही चश्मा है। तुम कमियाँ देखना बंद कर देते हो, और जो है उसकी अंधाधुंध सुंदरता दिखती है।", category: "Bedtime", readTime: 3),
            Story(title: "आज का तोहफा", content: "एक पुरानी कहावत है — कल इतिहास है, कल एक रहस्य, और आज एक तोहफा। इसीलिए इसे 'वर्तमान' कहते हैं! तुम अभी इसे खोल रहे हो। जो भी इसमें हो — यह तुम्हारा है। मैं तुम्हारे होने के लिए गहराई से कृतज्ञ हूँ।", category: "Short", readTime: 1)
        ],
        "Excited": [
            Story(title: "कहीं भी जाने का टिकट", content: "तुम्हारी आँखों में चमक देख रही हूँ! याद है मुझे वो दिन जब मुझे एक जन्मदिन के कार्ड में ट्रेन का टिकट मिला था — कहीं भी जाने का। वो हल्का-सा घबराहट भरा, पर अद्भुत सा जो पेट में उठता है — वो असीमित संभावनाओं की भावना है। उसे पकड़ो, उत्साहित एक! दुनिया तुम्हारा इंतज़ार कर रही है।", category: "Short", readTime: 3),
            Story(title: "पहली बर्फ", content: "याद है बचपन में जब सुबह खिड़की पर दौड़ते और देखते — पूरी दुनिया सफेद हो गई? तुरंत बाहर जाने की, पहले पाँव के निशान बनाने की, जीभ पर बर्फ के टुकड़े पकड़ने की इच्छा — वो शुद्ध उत्साह था। उस बच्चे जैसे रोमांच को थामे रखो। नई चीज़ों से चौंको!", category: "Nature", readTime: 2),
            Story(title: "बेकरी की खुशबू", content: "सुबह-सुबह किसी छोटी बेकरी के पास से गुज़रना — मक्खन और चीनी की मीठी खुशबू! उस पहले गर्म टुकड़े का इंतज़ार — वो खुमारी अलग होती है। ज़िंदगी भी ऐसी ही है — हर मोड़ पर कोई मीठा पल इंतज़ार कर रहा है। इस उत्साह को जी भर के जियो!", category: "Funny", readTime: 2)
        ]
    ]

    // MARK: - Mandarin Stories (中文故事)

    private lazy var mandarinStories: [String: [Story]] = [
        "Happy": [
            Story(title: "欢乐的花园", content: "哦，亲爱的，你好！看到你的笑容让我心里感到非常温暖。你知道吗，快乐就像我春天时那个破旧的花园。我会花上几个小时，跪在地上拔草、种下微小不起眼的种子。有时我会怀疑它们是否会长大。但是，在一个明媚的早晨，整个院子会突然绽放出无尽的色彩——黄色的水仙、淡粉色的玫瑰，还有鲜艳的红郁金香在微风中摇曳。那就是快乐的感觉。它是你在内心深处默默培育的美好事物的突然绽放。今天就让自己沉浸在那阳光里吧。你配得上每一片花瓣。", category: "Nature", readTime: 3),
            Story(title: "惊喜的野餐", content: "你还记得我们去野餐，却发现整个野餐篮都落在厨房台面上的那次吗？哦，我们笑得肚子都疼了！最后我们吃了在小路边找到的野黑莓，在那棵巨大的老橡树的树荫下讲着愚蠢的笑话。那不是我们计划的丰盛午餐，但它却如此完美，因为我们在一起。有时最大的快乐不是来自完美的计划，而是来自我们与爱的人分享的那些自发、随性的瞬间。", category: "Funny", readTime: 2),
            Story(title: "飞舞的萤火虫", content: "当我还是个小女孩的时候，夏夜异常闷热，空中满是飞舞的萤火虫。它们在长长的草丛中起舞，就像一颗颗陨落的小星星，无声地闪烁着金色的光芒。我们会一直跑，跑到双腿发酸，小心翼翼地把它们捧在手心，只为看它们在我们的掌心里发光，迅速许个愿，然后让它们飞向黑暗的夜空。你现在美好的笑容让我想起了那同样的光芒——纯粹、神奇，充满了无尽的希望。", category: "Bedtime", readTime: 4)
        ],
        "Sad": [
            Story(title: "雨天的窗户", content: "过来，好孩子。让我把这条温暖厚实的毯子披在你的肩上。我能看到今天有一朵乌云笼罩着你。听听雨滴轻轻敲打着玻璃的声音。即使是天空，有时也需要哭泣，你知道吗？大地需要那场雨来洗去尘土，帮助深处的树根解渴。你的眼泪现在正在做同样的事情。它们在浇灌你的灵魂，洗去你一直背负的沉重。今天就陪我安静地坐在这里，直到太阳重新从云层后面探出头来，这是完全可以的。", category: "Comfort", readTime: 3),
            Story(title: "破碎的茶杯", content: "我曾经有一个精致美丽的瓷茶杯，它从我手中滑落，碎成了十几片。我感到非常伤心。但是你爷爷没有把它扔掉。他小心翼翼地帮我把它粘回去，并用亮金色的漆涂抹在裂缝上。他告诉我：“现在它变得更加美丽了，因为它有了一段历史。它在破碎后活了下来。”亲爱的，你现在可能感到心碎。但那些裂缝正是你金色力量的所在。因为你所经历的一切，你变得更加强大、更加美丽。", category: "Moral", readTime: 3),
            Story(title: "月亮的藏身处", content: "你知道吗？即使是那轮皎洁明亮的伟大月亮，有时也会消失。她被漆黑的夜空完全隐藏了起来。但她从未真正离开我们。她只是在休息，在阴影中静静地收集她的银色光芒，以便回归时能闪耀得更加明亮。当你感到悲伤时，躲藏一小会儿是完全可以的，我的爱。你不需要一直为这个世界发光。去休息吧。你的光芒很安全，当你准备好时，它会重新回来。", category: "Bedtime", readTime: 2)
        ],
        "Anxious": [
            Story(title: "古老的橡树", content: "和我一起深呼吸，深长而缓慢。用鼻子吸气，用嘴巴呼气。想象一片广阔宁静的森林，正中央有一棵古老巨大的橡树。狂风呼啸，树枝在猛烈的风暴中剧烈摇摆。但在泥土深处，那些树根紧紧扎根在坚固的岩石上。这棵树没有恐慌，它只是坚持住，让风暴从它身上掠过。你的焦虑不过是一场天气，我勇敢的孩子。你就是那棵树。把你的根扎得深一点。风暴总会耗尽力气并过去，而你依然会屹立在那里。", category: "Nature", readTime: 3),
            Story(title: "河流的流向", content: "理想情况下，生活本该像一条美丽的河流一样流淌。有时那条河流会在尖锐的岩石上湍急流过，有时又会平静地穿过绿色的草地。但水从不担心它要去向哪里——它只是相信这条路最终会引导它到达广阔宁静的海洋。你现在正试图控制水流，这让你精疲力尽。相信你的道路吧，亲爱的。你会到达你确切需要去的地方。暂时放下手里的桨，让水流带着你走吧。", category: "Moral", readTime: 3),
            Story(title: "奶奶的秘密口袋", content: "过去每当我感到害怕或紧张时，我都会在围裙口袋深处放一块非常光滑闪亮的河卵石。每当我的心跳开始加速时，我就会用拇指摩挲石头光滑的边缘，并轻声提醒自己：“一切都会过去的。我是安全的。”想象一下，我现在正把那块温暖的石头放在你的掌心里。把手指合拢。感受它的重量。今天无论何时当你心思纷乱时，轻轻握紧你的手，知道奶奶就在你身边陪伴着你。", category: "Comfort", readTime: 2)
        ],
        "Lonely": [
            Story(title: "繁星交响曲", content: "哦，我的宝贝。孤独的感觉可能会让人觉得无比寒冷和广阔。但我希望你今晚走到室外，抬头看看漆黑的夜空。你看到那数以百万计的星星了吗？每一颗都独自坐在冰冷黑暗的宇宙中，相隔数百万英里。然而，它们聚在一起，创造了足以慰藉整个世界的、最令人惊叹的闪亮星空。我们都生活在同一片天空下。你现在可能觉得自己是一颗孤独的星星，但你是美丽且相连的星座的一部分。你从来没有真正的孤单过。", category: "Bedtime", readTime: 4),
            Story(title: "隐形的红线", content: "有一个古老的传说，说有一条隐形的红线连接着那些注定要互相爱护和支持的人。它可以跨越海洋，度过漫长的岁月，但它永远、永远都不会断裂。哪怕当你独自坐在安静空荡的房间里，感到寂静沉重时，那条线依然紧紧地缠绕在你的心上，把它直接连接到我的心上，甚至连接到你尚未遇见的那些人的心上。在脑海里轻轻扯一下这根线吧，记住，我也在另一头回应你。", category: "Moral", readTime: 3),
            Story(title: "邮箱里的信", content: "当我还是一个独自生活在新城市的年轻女孩时，我常常感到无比的孤独。邮箱总是空空如也。于是，我开始给自己写温暖的信。我告诉自己所有我急需听到的美好话语：“你很善良，你很聪明，你深深地值得被爱。”几天后当它们寄到信箱时，感觉就像是老朋友给的一个拥抱。也许今天，你也可以成为自己最好的朋友。给自己写一封充满爱的信吧。你值得听到这些话。", category: "Comfort", readTime: 2)
        ],
        "Tired": [
            Story(title: "舒适的拼布被", content: "哦亲爱的，你看上去真的很疲惫。你的肩膀低垂，眼神沉重。让我告诉你关于我小时候我母亲亲手为我做的那条厚重的拼布被吧。它很重、很柔软，闻起来有淡淡的薰衣草和老雪松的味道。每当世界对我要求太多时，我就会爬到那条厚重的被子下面被遮盖，布料的重量让世界的重量都消失了。想象我现在正把那条被子严实地盖在你的身上。闭上眼睛。今天你不需要承担任何东西。只需好好休息。", category: "Comfort", readTime: 3),
            Story(title: "冬眠的熊", content: "想想雪山里那些巨大的灰熊吧。它们整整一个冬天都在睡觉，一动不动，任凭外面的雪在洞穴外越堆越高。它们不为自己的休息而道歉；它们不会因为没有出去觅食而感到内疚。它们骨子里深知，大量的休息才是它们生存的方式。我的宝贝，你也允许自己冬眠。休息绝不是软弱；这是积聚力量的终极表现。打个大大的哈欠，闭上眼睛吧。", category: "Bedtime", readTime: 2),
            Story(title: "窗台上的猫", content: "你有没有安静地坐着观察过一只家猫在温暖的阳光下睡觉？它们是最纯粹的休息大师。它们伸出前爪，打着大大的哈欠，丝毫不担心还有什么家务或邮件在等着它们。今天就唤醒你内心的那只猫吧。在家里找一个温暖安静的角落，蜷缩起来，然后只是……存在。当你醒来时世界依然会在那里，我保证。", category: "Funny", readTime: 2)
        ],
        "Angry": [
            Story(title: "雷阵雨", content: "我看到了你眼中猛烈的火焰，你的下巴咬得很紧。愤怒就像一场猛烈突然的雷阵雨。它在你胸膛里大声隆隆作响，闪电在你的脑海中划过，它要求被感知到。这很可怕，极具毁灭性，但这也是完全自然的。你不需要与风暴抗争。让雷声轰鸣，让倾盆大雨落下吧。但请永远记住，一场风暴最终它的雨水会耗尽。风暴过后，空气会闻起来很清新，大地也被冲洗干净。让愤怒穿过你的身体洗刷你。", category: "Nature", readTime: 3),
            Story(title: "滚烫的煤炭", content: "在我年轻的时候，我的脾气很急躁。有人曾经告诉我，抓住痛苦的愤怒不放，就如同为了把它扔向别人而紧紧握住一块燃烧发烫的煤炭。谁会被烧伤呢？只有你自己。你的双手、你的心、你的内心平静。我知道你觉得自己有理，也许你确实有理！但放下那块煤炭吧，亲爱的。让它跌落到泥土中。走开，让你自己的双手愈合。你配得到内心的宁静远甚于证明你是‘对的’。", category: "Moral", readTime: 2),
            Story(title: "乱涂乱画的纸", content: "每当我气得发疯又无法用语言表达时，我就会拿出一支粗大的黑蜡笔，在一张废纸上尽可能用力、剧烈地乱涂乱画。一圈又一圈，用力按下直到蜡笔都折断了！我会画出尖锐的线条和混乱的圆圈。你知道吗？那感觉是一种奇妙的耗尽。把你那猛烈的能量释放到一张纸上，远比让它在你的体内燃烧或伤害周围的人要好得多。找个时间试试看！拿出你最狂傲的那支蜡笔。", category: "Funny", readTime: 2)
        ],
        "Grateful": [
            Story(title: "感恩小瓶子", content: "哦，感恩是一种多么温暖、广阔的感觉啊！它让你的胸腔感到轻盈。让我跟你讲讲我那个旧的玻璃感恩瓶吧。每天傍晚，我都会拿一张小纸条，写下一件我感激的微小事物。不是像升职或新房子这种大事，而是比如‘一个非常熟透的桃子’或者‘雨水落在炎热路面上的味道’。一年后，瓶子都溢出来了。当你训练你的眼睛去寻找微小的奇迹时，你会突然发现它们散落在你周围的每一个角落。", category: "Moral", readTime: 3),
            Story(title: "金色的眼镜", content: "想象一下此时我递给你一副古董般的、神奇的金色眼镜。当你把它们戴在脸上的那一刻，所有你爱的事物都会散发出柔和、温暖、耀眼的光芒。你手中的咖啡杯在发光。你脚边忠诚的小狗在发光。窗外照射进来的阳光在明亮地发光。感恩不过就是戴上这副隐形的金色眼镜。你突然不再看到那些残缺的东西，你会被你已经拥有的一切事物散发出的夺目光辉所包围。", category: "Bedtime", readTime: 3),
            Story(title: "今日的礼物", content: "有一句古老的谚语我一直放在心底：‘昨天已成为历史，明天是未知的谜团，而今天则是一份绝对的礼物。’这正是为什么我们称之为‘Present’(礼物/现在) 原因所在！你现在正在拆开今天的礼物。无论它包含什么——不管是挑战还是简单的快乐——它都是你所活着的证明。我深深感谢你在这一刻，坐在这里与我如此宝贵地分享这个瞬间。", category: "Short", readTime: 1)
        ],
        "Excited": [
            Story(title: "去往任何地方的车票", content: "哦，我能看到你眼中那绝对带电的火花！你让我想起我发现夹在一张旧生日贺卡里的那张火车票的那天。那是一张通往我想去的任何地方的车票。你知道那种在胃里翻腾的、微微紧张却又奇妙轻盈的感觉吗？那是纯粹无尽的可能性的感觉。带着它奔跑吧，我爱冒险的孩子！让这种兴奋像强风一样把你带起。世界如此广阔，正等着你跨出大门。", category: "Short", readTime: 3),
            Story(title: "第一场初雪", content: "你还记得小时候清晨醒来冲到窗前，看到整个世界变成了一片纯洁、闪闪发光的白色的那种无与伦比的魔力吗？泥土和道路都被安静的厚雪覆盖。那种想立刻冲到外面、成为第一个留下脚印的人、在舌尖接住一片冰冷的雪花的冲动——这就是纯粹的、纯真的兴奋。紧紧握住这种孩子般的惊奇。让自己为新事物感到战栗吧！", category: "Nature", readTime: 2),
            Story(title: "面包店的香气", content: "没有什么比清晨经过社区里的小面包店更美妙的事情了。浓郁的黄油味、酵母和温糖的香气飘出门外，将你环绕。走进店里，期待着咬下第一口热气腾腾、松脆可口的面包时的那种期盼感令人陶醉！亲爱的，生活充满了甜蜜美味的时刻，它们就躲在拐角处等着你去品尝。尽情享受这生机勃勃的期待吧！", category: "Funny", readTime: 2)
        ]
    ]

    // MARK: - Spanish Stories (Cuentos en Español)

    private lazy var spanishStories: [String: [Story]] = [
        "Happy": [
            Story(title: "El Jardín de la Alegría", content: "¡Oh, hola querido mío! Me alegra tanto el corazón verte sonreír. Sabes, la felicidad es como mi viejo jardín en primavera. Pasaba horas de rodillas, arrancando malas hierbas y plantando semillas diminutas y sin pretensiones. A veces me preguntaba si algo crecería. Pero entonces, una mañana brillante, todo el patio estallaba de color: narcisos amarillos, suaves rosas rosadas y radiantes tulipanes rojos meciéndose con la brisa. Así se siente la alegría. Es el florecimiento repentino de todas las cosas buenas que has estado cultivando en silencio dentro de ti. Déjate bañar por esa luz hoy. Te has ganado cada pétalo.", category: "Nature", readTime: 3),
            Story(title: "El Picnic Sorpresa", content: "¿Recuerdas cuando fuimos de picnic y nos dimos cuenta de que habíamos dejado toda la cesta en la encimera de la cocina? ¡Oh, nos reímos tanto hasta que literalmente nos dolió la barriga! Terminamos comiendo moras silvestres que encontramos cerca del sendero y contando chistes tontos bajo la sombra de aquel enorme y viejo roble. No fue el almuerzo elegante que planeamos, pero fue absolutamente perfecto porque estábamos juntos. A veces, la mayor alegría no proviene de un plan perfecto, sino de los momentos espontáneos y un poco desordenados que compartimos con las personas que amamos.", category: "Funny", readTime: 2),
            Story(title: "Las Luciérnagas Danzantes", content: "Cuando era niña, las noches de verano eran cálidas y estaban llenas de luciérnagas. Bailaban sobre la hierba alta como diminutas estrellas fugaces parpadeando sus canciones mudas y doradas. Corríamos hasta que nuestras piernas se cansaban, atrapándolas suavemente con las manos formando un cuenco solo para verlas brillar contra nuestras palmas, pedir un deseo rápido y dejarlas volar hacia el cielo oscuro. Tu maravillosa sonrisa en este momento me recuerda exactamente a esa misma luz: pura, mágica y llena de una esperanza infinita.", category: "Bedtime", readTime: 4)
        ],
        "Sad": [
            Story(title: "La Ventana Lluviosa", content: "Ven aquí, mi dulce niño. Déjame arroparte los hombros con esta manta gruesa y cálida. Puedo ver que hoy tienes una nube gris sobre ti. Escucha cómo la lluvia golpea suavemente el cristal. Hasta el cielo necesita llorar a veces, ¿no lo sabías? La tierra necesita esa lluvia para limpiar el polvo de las cosas y ayudar a las raíces profundas a beber. Tus lágrimas están haciendo exactamente lo mismo ahora mismo. Están regando tu alma y lavando las cosas pesadas que has estado cargando. Está perfectamente bien sentarnos aquí en silencio hasta que el sol decida asomarse nuevamente.", category: "Comfort", readTime: 3),
            Story(title: "La Taza Rota", content: "Una vez tuve una delicada y hermosa taza de porcelana que se me resbaló de las manos y se hizo pedazos. Me sentí tan devastada. Pero tu abuelo no la tiró. Me ayudó a pegarla con mucho cuidado y pintó las grietas con laca dorada brillante. Me dijo: 'Ahora es aún más hermosa porque tiene una historia. Sobrevivió después de romperse'. Puede que te sientas roto en este momento, mi amor. Pero es en esas grietas donde reside tu fortaleza dorada. Eres mucho más fuerte y hermoso por todo lo que has superado.", category: "Moral", readTime: 3),
            Story(title: "El Escondite de la Luna", content: "¿Sabías que incluso la gran y brillante luna a veces desaparece? Queda completamente oculta por el oscuro cielo nocturno. Pero en realidad nunca nos deja. Simplemente está descansando, reuniendo su luz plateada en silencio entre las sombras para poder regresar y brillar con aún más fuerza. Está perfectamente bien esconderse un poquito cuando te sientes triste, mi amor. No tienes que brillar constantemente para el resto del mundo. Solo descansa. Tu luz está a salvo y volverá cuando estés listo.", category: "Bedtime", readTime: 2)
        ],
        "Anxious": [
            Story(title: "El Viejo Roble", content: "Respira conmigo, profundo y lento. Inhala por la nariz, exhala por la boca. Imagina un bosque inmenso y silencioso, y justo en el centro se alza un roble gigantesco y milenario. El viento aúlla y las ramas se agitan de un lado a otro en medio de una tormenta feroz. Pero bajo la tierra, sus raíces se aferran fuertemente a la roca sólida. El árbol no entra en pánico; solo se sujeta y deja que la tormenta pase por encima. Tu ansiedad es simplemente el clima, mi valiente. Tú eres el árbol. Húndete en tus raíces. La tormenta se agotará y pasará, pero tú seguirás en pie.", category: "Nature", readTime: 3),
            Story(title: "El Fluir del Río", content: "Idealmente, se supone que la vida fluye como un río hermoso y constante. A veces ese río choca violentamente contra rocas afiladas, y otras veces serpentea con calma por verdes prados. Pero el agua nunca se preocupa por hacia dónde se dirige, simplemente confía en que el cauce la guiará finalmente hacia el inmenso y pacífico océano. Ahora mismo estás tratando de controlar el cauce, y eso te está agotando. Confía en tu camino, mi cielo. Llegarás exactamente a donde necesites estar. Suelta los remos por un momento y deja que la corriente te lleve.", category: "Moral", readTime: 3),
            Story(title: "El Bolsillo Secreto de la Abuela", content: "Solía llevar una piedra de río muy pulida y suave en el bolsillo de mi delantal cada vez que sentía miedo o nervios. Cada vez que mi corazón empezaba a latir deprisa, trazaba los bordes con mi pulgar y me recordaba en voz baja: 'Esto también pasará. Estoy a salvo'. Imagina que estoy poniendo esa misma piedra cálida en la palma de tu mano en este instante. Cierra los dedos, apriétalos. Siente su peso. Siempre que tu mente empiece a acelerarse hoy, aprieta la mano suavemente y recuerda que tu Abuela está aquí contigo.", category: "Comfort", readTime: 2)
        ],
        "Lonely": [
            Story(title: "La Sinfonía de las Estrellas", content: "Oh, mi niño precioso. La soledad puede sentirse inmensa y espantosamente fría. Pero quiero que esta noche salgas y mires el cielo oscuro. ¿Ves todos esos millones de estrellas? Cada una está sola en la oscuridad gélida del espacio, separada por millones de millas de las demás. Sin embargo, juntas, crean un manto brillante e impresionante que reconforta a todo el mundo. Todos nos hallamos bajo ese mismo cielo. Puedes sentirte como una sola estrella ahora mismo, pero eres parte de una hermosa constelación conectada. Nunca estás verdaderamente solo.", category: "Bedtime", readTime: 4),
            Story(title: "El Hilo Invisible", content: "Cuenta una antigua leyenda que existe un hilo rojo invisible que conecta a todas las personas que están destinadas a amarse y apoyarse mutuamente. Puede cruzar océanos y extenderse a lo largo del tiempo, pero nunca, nunca se rompe. Incluso cuando estés sentado en una habitación vacía y tranquila y el silencio se sienta insoportable, ese hilo sigue firmemente atado a tu corazón, conectándolo directamente al mío, y a los corazones de personas que aún no has conocido. Tira un poco de él en tu imaginación, y sabe que yo también estoy tirando desde aquí.", category: "Moral", readTime: 3),
            Story(title: "La Carta en el Correo", content: "Cuando era una joven mujer que vivía sola en una nueva ciudad, solía sentirme increíblemente sola. Los buzones de correo siempre estaban vacíos. Así que comencé a escribirme amables cartas a mí misma. Me decía todas las cosas maravillosas que necesitaba escuchar desesperadamente: 'Eres amable, eres inteligente, eres sumamente digna de recibir amor'. Y cuando llegaban al buzón días después, se sentía como el abrazo de un querido amigo. Quizás hoy también puedas ser tu mejor amigo. Escríbete una nota de amor a ti mismo. Te mereces escucharla.", category: "Comfort", readTime: 2)
        ],
        "Tired": [
            Story(title: "La Cobija de Retazos", content: "Oh, cariño mío, te ves tan fatigado. Tus hombros están caídos y tus ojos pesados. Déjame contarte sobre la colcha de retazos que mi madre hizo a mano para mí cuando era niña. Era gruesa, suave y olía ligeramente a lavanda y a cedro antiguo. Cada vez que el mundo me exigía demasiado, me escondía bajo esa colcha pesada, y el peso de su tela lograba hacer que el peso del mundo se esfumara. Imagina que ahora mismo arropo esa cobija amarrándola segura sobre ti. Cierra los ojos. Hoy no tienes que cargar con nada. Solo descansa.", category: "Comfort", readTime: 3),
            Story(title: "El Oso que Inverna", content: "Piensa en un gran oso pardo subiendo a las cumbres nevadas. Duermen durante todo el invierno, manteniéndose muy quietos y permitiendo que la nieve se amontone a montones fuera de sus rincones. No se disculpan por tomar un respiro; no sienten culpabilidad ni remordimiento de no salir a de un bosque helado para cazar. Saben profundamente en el instinto que ese inmenso reposo es exactamente lo que garantiza su supervivencia. Se te permite invernar maravillosamente mi niño bello. Descansar no es un síntoma de vulnerabilidad; es el acto supremo donde renuevas la fuerza para continuar. Tantea un inmenso bostezo y cierra tus ojos.", category: "Bedtime", readTime: 2),
            Story(title: "El Gato en el Alféizar", content: "¿Alguna vez te has sentado en silencio a observar cómo duerme un gato sobre el sofá bajo un cálido charco de luz solar? Elloss son los más puros y verdaderos maestros del descanso. Estiran sus patas, se dan un amplio bostezo, y no cuentan con ninguna preocupación en torno de los quehaceres ni los correos que puedan agobiar a los seres humanos. Inspírate como los mininos durante el día de hoy. Busca tu rincón hogareño, escóndete calentito y... simplemente, vive el reposo absoluto. Garantizo que ese duro mundo estará esperando tu retorno a la vuelta del amanecer.", category: "Funny", readTime: 2)
        ],
        "Angry": [
            Story(title: "La Tormenta Eléctrica", content: "Veo el fuego feroz arder en tus pupilas, y cómo sostienes apretada esa mandíbula. Estar bajo el enojo nos hace sentir justamente como inmersos en una incontrolable, intempestiva tormenta repleta de furia. Retumbos violentos colisionan tu coraje contra las emociones que destellan de tu relampagueada mente con la imperiosa necesidad que esto se haga ser captado y comprendido a totalidad. ¡Podría aterrar bastante, claro! y asombrosamente resulta tan meramente consustancial. Acoge ser tempestad y no la apacigües en contención y riña con esa ira de lluvia, deja que suceda la estrepitosa ventisca, con su trueno, un agua diluvio en abundancia que purifica tu entorno interior. Un chaparrón, después de desatar torbellinos, pronto queda despoblado de un llanto acuífero; para revelarse ante las esferas celestiales impregnando oxigenadas y perfumadas auras; lavando las penurias y opacidades. Confía este enojo lavándote profundo hasta tu ser impoluto.", category: "Nature", readTime: 3),
            Story(title: "El Carbón al Rojo Vivo", content: "En los tiempos de mi mocedad solía retener impetuosas erupciones volcánicas como arrebatos iracundos. Aquello enseñome que una fiera indignación contenida es estrictamente coger por voluntad tuya ardientes brasas de rocas vivas para lanzarlo y cobrar represalia contra esos adversarios culpables. Con gran infortunio pregunto... ¿Sabes a quién consumen ésas llagas dolorosas en primera orden? A tus dedos, corazón y al espíritu de tus calmas de razonamiento. No me es incrédulo presagiar lo merecida y excusable tu rabia pueda representar de momento ante esas afrentas. Libera y lanza tu ascua ardiente mi amor; regala que precipiten inertes hacia el suelo para aliviar tan graves cicatrices en tí mismo. Opta en buscar y disfrutar refugio para paz propia antes y en vez obtener siempre el veredicto para un juicio que solo demuestre tener poseído tú, toda toda la pura razón moral.", category: "Moral", readTime: 2),
            Story(title: "Las Hojas de Garabatos", content: "Para calmar efluvios de bilis alterada y exclamar palabras amargas por un escozor rabioso sin salida idónea a articular los vocablos coherentes... tomaba el plumón rotulador negro e impulsiva pintaba líneas en desasosiegos o gruesas siluetas muy agobiantes. Rasgando y girando muy contundente con trazos furiosos sobre una lámina reciclad de papel barato hasta destrozar aquella punta coloreada, desgarraba con remolinos caóticos o contornos agresivos. Comprendía entonces al terminar algo tan maravillosamente agostado: Descargarse así nos entrega y alivia mucha tensión corporal sin provocar heridas hacia aquéllos otros, en contra del fuego interior si esto es consumido sin catarsis y desaire.", category: "Funny", readTime: 2)
        ],
        "Grateful": [
            Story(title: "El Frasco del Agradecimiento", content: "Ah, ¡es reconfortante percibir cómo tu espíritu liviano asciende desde estar bajo un cálido regazo llamado gratitud en plena exaltación! Sientes flotante los senos del aliento. Te recuerdo lo entrañable narrado referente a mi viejo contenedor encristalado para Guardar mi Apreciaciones. Adquirí el hábito religioso donde una caída la tarde arranco un minúsculo tramo papelero describiendo apenas lo agradecido minúsculo detalle gozoso para hoy. No me jacté al encriptar gloriosas promesas corporativas logradas, simplemente lo reducía hacia un humilde dulzor maduro sabrosísimo aportado a ser 'un tierno fruto frutal de duraznero' o el asfalto aromático húmedo deslavado del vapor lluvioso. Transcurrido el curso estacional, dicho continente sobrepasaba del colmo al borde desbordante. Observas con óptica educada y te percatas cómo es regocijarse reconociendo un milagro inmenso expandido sutil sobre nuestro diario paradero trivial.", category: "Moral", readTime: 3),
            Story(title: "Los Espejuelos Dorados", content: "Dedica un suspiro instantáneo, evoca poseas y ubiques encima tus pupilas unos antiguos pero majestuosos gafa lente bañado del oro bruñido donde al visualizar con asombro; aquello amado u originado, emitiría instantáneamente los rebotes dorados radiantes luminosos. ¿Tostaba café esmaltando una porcelana? Emanó aúreos brillos. Ese compañero fiel de lomo y cuatro pezuñas descasando a pie ¿Resplandecía un brillo? Aquellos cálidos vitrales cruzados durante aquel encuadre en soleada ventolera, ¿te lucían encandiladores refulgentes también? Apreciar lo venturoso gratificante corresponde exclusivamente acomodar los míticos y fantasiosos visores, logrando difuminar opacidades, dejando imperceptibles las fallas u ausencias no existentes sobre cosas o las aspiraciones jamás poseídas. Vivimos entonces inmensas majestuosas bendiciones ofrendada con lo propio del ya vivir gozándolas plenitud resplandecida.", category: "Bedtime", readTime: 3),
            Story(title: "El Regalo de Hoy", content: "Considero como aforismo de sabiduría este lema acurrucado bien de a adentro al centro del espíritu mío: Un ayer remoto que forma lección antigua historia fenecida; el tiempo próximo encierra lo sorpresivamente irresoluto o lo incomprensiblemente ocultado... no obstante aquello palpable en nuestra transcurrir contemporáneo del vivaz HOY... se obsequia ¡Una grandiosa ofrenda bondadosa, o lo es el “Presente”! Éste te rodea y le quitas sus moños desempaquetado sus hermosos adornos. Aquella aventura interior te desafía retos, un amargo pero valioso trayecto hasta colmar con risueñas simples jovialidades, para ti otorgado; te incumbe tomar rienda del vivir sin postergaciones. Gozosa del milagro y gracia bendigo el tiempo concedido por tí... permaneciendo allí ubicándote justo frente mis regazos abrazos para tan hermosamente estar, interactuando lo glorioso actual e infinito instante junto nuestra existencia tuya.", category: "Short", readTime: 1)
        ],
        "Excited": [
            Story(title: "El Boleto a Cualquier Parte", content: "¡Ay, me atrevería asegurar apreciar resplado electrizante brotando de asombrosa brillantez tus maravilladas luceros ojitos! Son reminiscencias en alusión memorativa a tiempos mozos donde, entre mis antiguas guardadas reliquias descubro, un pasaje impreso arrinconado entre viejo pergamino celebrativo aniversario cumpleaños a punto ser extintado. Fue una libreta permitiendo trasladarme incursionando tierras hacia “La geografía total ilusionada anhelada a desear pasear”. Rememoras lo inigualable del burbujeante mariposeo vibrante sintiéndose nerviosamente inquieto... y un encanto libre flotador gravitando adentro toda tú entraña estomacal ? Difiérelo ser “Lo Incalculable posibilidad e ilimitadas alternativas abarcantes”. Haz uso y cabalga aventurero soñador... toma carrera a esas brisas motivacionales inusitadas dejando acariciarle todo tu vuelo corporal como al huracán poderoso, amarrando el empujón propulsor incitante al descubrimiento vastamente interminablemente amplio; apostando esperarse nomás abriertando el pórtico frontal del andador doméstico de lo tuyo.", category: "Short", readTime: 3),
            Story(title: "La Primera Nevada", content: "Te traería remembranza el inexplicable prodigioso milagro de una mañana despertándose un infante inocente pequeño, agolparse presuroso trasluzciendo su escarcha vidriero de ventanales con asombro viendo el absoluto paisaje exterior reconvertido inmaculado recubrimiento espléndidamente albo nieve parpadeado resplandeciendo ? Carreteras lodosas disipadas, alfombras silentes cobijaron lo ordinario. Invasora la incansable excitación anhelante ser empujadita exteriorizarte arropándote para corretear saltarina... Ser dueña privilegiada abriendo las rutas con las únicas marcas pisoteadas recién primerizas, cazadora lengua gélida lamiendo lo cristalizado y un fractal escarchado desvaneciendo tus sabores enfríos – Tal manifestación denota exultante emoción sin disuadir alocadas desproporciones extasiadas. Abraza el respiro infantil acaudalando tus pasiones alborozadas bien aferrándote tenaz por vivir lo deslumbrado maravillado ante la innovada creatividad del descubrir.", category: "Nature", readTime: 2),
            Story(title: "Olores de Panadería", content: "¿Resulta equiparable a cruzar las angosturas empedradas transitando mañanas adormilantes rodeándose esquinas por los arrabales vecinales rumbo un despacho horneadas bollerías ? Resultante emanaciones embriagadoras invaden pesadas densidades azucaradas tibias levaduras enlazándolas mantecosidades saturantemente acariciantes exhalando de aperturas y resquicios cobijando un trance al paso del transeúnte; dejándole suspendido. Ese gozo expectante por aproximarse ansiosamente entrar adquiriendo esa crocante calidez al tacto bocadillos crujientes saboreando deleitable primer pedazo resulta embrujador inebriando placenteramente. Comprende esto queridísima vida; provee un torrente surtido colmándose dulzonas inmensurables maravillosidades esquivándose las rendijas cruces giratorias acechándole tú probatoria curiosidad de un mordisco engalanado la vida. Degusta con ansiosa gozosa vida su alboroto esperanzador y vibrante presentimiento festejador inagotable !.", category: "Funny", readTime: 2)
        ]
    ]

    // MARK: - French Stories (Histoires en Français)

    private lazy var frenchStories: [String: [Story]] = [
        "Happy": [
            Story(title: "Le Jardin de la Joie", content: "Oh, bonjour ma chérie ! Cela met tellement de chaleur dans mon cœur de te voir sourire. Tu sais, le bonheur, c'est comme mon vieux jardin au printemps. Je passais des heures à genoux, à arracher les mauvaises herbes et à planter de minuscules graines sans prétention. Parfois, je me demandais si quelque chose pousserait un jour. Mais ensuite, un beau matin lumineux, toute la cour explosait de couleurs——des jonquilles jaunes, des roses d'un rose doux et des tulipes d'un rouge vif qui se balançaient dans la brise. C'est ce que l'on ressent avec la joie. C'est l'éclosion soudaine de toutes les bonnes choses que tu as cultivées tranquillement en toi. Laisse-toi baigner dans ce soleil aujourd'hui. Tu as mérité chaque pétale.", category: "Nature", readTime: 3),
            Story(title: "Le Pique-nique Surprise", content: "Te souviens-tu de la fois où nous sommes allés pique-niquer et que nous avons réalisé que nous avions laissé tout le panier sur le comptoir de la cuisine ? Oh, nous avons tellement ri que nous en avions mal au ventre ! Nous avons fini par manger des mûres sauvages que nous avions trouvées près du sentier et par raconter des blagues stupides à l'ombre de cet immense vieux chêne. Ce n'était pas le déjeuner chic que nous avions prévu, mais c'était absolument parfait parce que nous étions ensemble. Parfois, la plus grande joie ne vient pas d'un plan parfait, mais des moments spontanés et un peu désordonnés que nous partageons avec les gens que nous aimons.", category: "Funny", readTime: 2),
            Story(title: "Les Lucioles Dansantes", content: "Quand j'étais petite fille, les nuits d'été étaient épaisses de chaleur et remplies de lucioles. Elles dansaient sur les hautes herbes comme de minuscules étoiles filantes clignotant leurs chansons dorées et silencieuses. Nous courions jusqu'à en avoir les jambes fatiguées, les attrapant doucement dans nos mains en coupe juste pour les voir briller contre nos paumes, en faisant un petit vœu, et en les laissant s'envoler vers le ciel sombre. Ton merveilleux sourire en ce moment me rappelle exactement la même lumière : pure, magique et pleine d'un espoir infini.", category: "Bedtime", readTime: 4)
        ],
        "Sad": [
            Story(title: "La Fenêtre Pluvieuse", content: "Viens ici, ma douce enfant. Laisse-moi glisser cette couverture chaude et lourde sur tes épaules. Je peux voir un nuage gris planer au-dessus de toi aujourd'hui. Écoute la pluie taper doucement contre la vitre. Même le ciel a besoin de pleurer parfois, ne le savais-tu pas ? La terre a besoin de cette pluie pour laver la poussière et pour aider les racines profondes à boire. Tes larmes font exactement la même chose en ce moment. Elles abreuvent ton âme et lavent les choses lourdes que tu as portées. Tu as parfaitement le droit de rester assise ici en silence avec moi jusqu'à ce que le soleil décide de pointer son nez à travers les nuages à nouveau.", category: "Comfort", readTime: 3),
            Story(title: "La Tasse Cassée", content: "J'avais autrefois une délicate et belle tasse de thé en porcelaine qui m'a glissé des mains et s'est brisée en mille morceaux. J'étais tellement anéantie. Mais ton grand-père ne l'a pas jetée. Il m'a aidée à la recoller avec soin, et il a recouvert les lignes de faille avec une brillante laque d'or. Il m'a dit : « Maintenant, elle est encore plus belle parce qu'elle a une histoire. Elle a survécu à la casse. » Tu pourrais te sentir brisée en ce moment, mon amour. Mais ces fissures sont l'endroit où vit ta résilience dorée. Tu es d'autant plus forte et plus belle en raison de tout ce que tu as surmonté.", category: "Moral", readTime: 3),
            Story(title: "La Cachette de la Lune", content: "Savais-tu que même la grande et brillante lune disparaît parfois ? Elle est complètement cachée par le ciel nocturne sombre. Mais en réalité, elle ne nous quitte jamais. Elle se repose simplement, rassemblant sa lumière argentée dans le calme des ombres afin de pouvoir revenir briller d'un éclat encore plus vif. C'est tout à fait normal de te cacher un petit moment quand tu te sens triste, mon amour. Tu n'es pas obligée de briller en permanence pour le reste du monde. Repose-toi simplement. Ta lumière est en sécurité, et elle reviendra lorsque tu seras prête.", category: "Bedtime", readTime: 2)
        ],
        "Anxious": [
            Story(title: "Le Vieux Chêne Ancien", content: "Respire avec moi, profondément et lentement. Inspire par le nez, expire par la bouche. Imagine une vaste forêt silencieuse, et juste au centre, un vieux et massif chêne. Le vent hurle, et les branches se balancent avec fureur dans une violente tempête. Mais sous la terre, ces racines sont fermement agrippées à la roche solide. L'arbre ne cède pas à la panique ; il s'accroche et laisse la tempête passer sur lui. Ton anxiété n'est qu'un climat temporaire, mon courageux enfant. Tu es cet arbre. Enfouis tes racines plus profondément. La tempête va s'essouffler et passer, mais toi, tu seras toujours debout.", category: "Nature", readTime: 3),
            Story(title: "Le Courant de la Rivière", content: "Idéalement, on suppose que la vie s'écoule comme une rivière belle et continue. Parfois cette rivière se heurte violemment à des roches pointues, et d'autres fois elle serpente calmement à travers des prés verdoyants. Mais l'eau ne se préoccupe jamais de savoir où elle va, elle a simplement la foi que le chemin la conduira finalement vers l'immense et paisible océan. Tu es en train d'essayer de contrôler l'eau en ce moment, et cela t'épuise. Fais confiance à ton chemin, ma chérie. Tu arriveras exactement là où tu dois être. Lâche les rames un instant et laisse le courant te porter.", category: "Moral", readTime: 3),
            Story(title: "La Poche Secrète de Grand-mère", content: "J'avais l'habitude de garder un galet de rivière très lisse et poli au fond de la poche de mon tablier chaque fois que je me sentais effrayée ou nerveuse. À chaque fois que mon cœur se mettait à battre trop vite, je passais mon pouce sur ses bords lisses et je me rappelais tout bas : « Cela aussi passera. Je suis en sécurité. » Imagine que je place cette même pierre chaude dans la paume de ta main à l'instant même. Referme tes doigts dessus. Sens son poids. Chaque fois que ton esprit s'emballera aujourd'hui, serre doucement ta main et sache que Grand-mère est là, juste à côté de toi.", category: "Comfort", readTime: 2)
        ],
        "Lonely": [
            Story(title: "La Symphonie des Étoiles", content: "Oh, ma précieuse. La solitude peut sembler si effroyablement froide et immense. Mais ce soir, je veux que tu ailles dehors et que tu regardes le ciel sombre. Est-ce que tu vois ces millions d'étoiles ? Chacune d'elles est assise seule dans l'obscurité glaciale de l'espace, séparée par des millions de kilomètres. Et pourtant, ensemble, elles créent la couverture la plus époustouflante et scintillante qui réconforte le monde entier. Nous sommes tous sous ce même ciel. Tu as peut-être l'impression d'être une étoile solitaire en ce moment, mais tu fais partie d'une constellation magnifique et connectée. Tu n'es jamais vraiment seul.", category: "Bedtime", readTime: 4),
            Story(title: "Le Fil Invisible", content: "Il existe une vieille légende ancienne qui dit qu'un fil rouge invisible relie ceux qui sont destinés à s'aimer et à se soutenir mutuellement. Il peut s'étirer par-delà les océans et traverser les années, mais il ne se brise jamais, au grand jamais. Même lorsque tu es assise dans une chambre silencieuse et vide et que le silence te semble pesant, ce fil est fermement attaché autour de ton cœur, le reliant directement au mien, et au cœur des personnes que tu n'as même pas encore rencontrées. Tire un peu dessus dans ton esprit, et sache que je tire en retour.", category: "Moral", readTime: 3),
            Story(title: "La Lettre dans le Courrier", content: "Quand j'étais une jeune femme vivant seule dans une nouvelle ville, je me sentais parfois incroyablement seule. Ma boîte aux lettres était toujours vide. Alors, j'ai commencé à m'écrire des lettres réconfortantes à moi-même. Je me disais toutes les choses merveilleuses dont j'avais désespérément besoin d'entendre : « Tu es gentille, tu es intelligente, tu es profondément digne d'être aimée. » Et quand elles arrivaient par la poste des jours plus tard, c'était comme recevoir un câlin d'un ami cher. Peut-être qu'aujourd'hui, tu pourrais être ton propre meilleur ami, toi aussi. Écris-toi une note d'amour. Tu mérites de l'entendre.", category: "Comfort", readTime: 2)
        ],
        "Tired": [
            Story(title: "L'Édredon Douillet", content: "Oh ma chérie, tu sembles si épuisée. Tes épaules s'affaissent et tes yeux sont lourds. Laisse-moi te parler de la couverture en patchwork épaisse que ma mère a cousue à la main pour moi lorsque j'étais enfant. Elle était lourde, douce, et sentait légèrement la lavande et le vieux cèdre. Chaque fois que le monde exigeait trop de moi, je me glissais sous cette lourde couverture, et le poids du tissu faisait disparaître le fardeau de la vie. Imagine-moi en train de border cette couverture tout autour de toi en ce moment. Ferme les yeux. Tu n'as pas à porter quoi que ce soit aujourd'hui. Repose-toi simplement.", category: "Comfort", readTime: 3),
            Story(title: "L'Ours qui Hiberne", content: "Pense à ces immenses grizzlys des hautes montagnes enneigées. Ils dorment tout l'hiver, dans l'immobilité la plus totale, laissant la neige s'accumuler en tas à l'extérieur de leurs tanières. Ils ne s'excusent pas de se reposer ; ils ne ressentent aucune culpabilité à ne pas sortir à la recherche de nourriture. Ils savent au fond de leurs os qu'un grand repos est exactement ce dont ils ont besoin pour survivre. T'as le droit d'hiberner, mon cœur. Se reposer n'est pas une faiblesse ; c'est l'acte ultime de rassembler ses forces. Lâche un grand bâillement et ferme les yeux, tout simplement.", category: "Bedtime", readTime: 2),
            Story(title: "Le Chat sur le Rebord de la Fenêtre", content: "T'es-tu déjà assise en silence pour contempler un petit chat de maison faisant la sieste dans une chaude flaque de soleil ? Ils sont les maîtres incontestés du repos absolu. Ils étirent leurs pattes avant en faisant un long bâillement, et ne nourrissent strictement aucune inquiétude quant aux corvées ménagères ou aux courriels qui les attendent. Approprie-toi l’âme du chat aujourd'hui. Trouve une place tranquille chez toi, mets-toi en boule, et... reste là. Le monde sera toujours là quand tu te réveilleras, je t'en fais la promesse.", category: "Funny", readTime: 2)
        ],
        "Angry": [
            Story(title: "L'Orage Électrique", content: "Je vois cette petite lueur incendiaire dans tes yeux, et ta lèvre supérieure se referme très fort. Être en furie ressemble comme par coïncidence à traverser brusquement un terrible orage déchaîné. Les grondements résonnent fort aux portes de ta poitrine ! L'éclair explose dans le cerveau s'attendant expressément d'être libéré et écouté avec attention. C'est effroyable pour tous mais aussi d'une nature parfaitement physiologique. Évite de faire la guerre aux typhons inévitables. Permets aux pluies tombantes et à l’effervescence tonitruante d'agir. Toutefois retiens une vérité primordiale :  Les nuages les plus gorgés tarissent de trombes d'eau. La fureur nettoyée purifie les espaces saturés sous un oxygène pur en nous rendant notre beauté limpide. Donne vie entière au fléau des cris internes.", category: "Nature", readTime: 3),
            Story(title: "Le Charbon Ardent", content: "Durant les chapitres de ma jeune adolescence, mes éclats de passion et rancœur semblaient incontrôlables ! Une source très inspirante de mon école a pu me démontrer un soir l'allégorie de tenir par hostilité notre brûlure vindicative en reprenant au creux de la paume le charbon chauffé et incandescent prêt à foudroyer tous nos démons ennemis . Répond-donc avec justesse : Quelle personne reçoit le brasier de chaleur brulante en fin de compte sur les dix phalangettes du propre membre amputé d'esprit de douceur ? Exact ! Tes fragiles extrémités manuelles et ton intérieur moral . Si te paraît très recevable ton accès de rancune ce n'est rien comparé au simple choix libérateur... Cède ton boulet charbonnier aux sables froids, libère tes blessures car posséder une harmonieuse paix l'emporte toujours grandement par-dessus 'être totalement détenteur authentique d'avoir eu absolument Raison'.", category: "Moral", readTime: 2),
            Story(title: "Les Gribouillis Hystériques", content: "Pour faire dissiper mes aigreurs stomacales et tempérer l'assaut verbieux d'insultes bloquées sans chemin vocal disponible : je m'agrippais contre un grand bâton ou grand pastel cireux noir au but barbouiller follement de gigantesques tracés sauvages pleins d'assouvissement contre notre ennemi le feuillet recyclé peu coûteux . Tournant furieusement le manche cassant parfois la texture friable grasse par force brutale de pressage compulsif . Il s'édifie d'horriblement sombres lignes barbares affreuses. Est-ce concluant ? Et oui, on finit magiquement épris d'un épuisement musculaire divin. Ce refoulement expulsé avec agression sous un cahier a tellement plus d’effets guérisseurs face au maintien consumériste destructif ou le rejet contre le prochain de votre entourage quotidien. Pourquoi ne pas expérimenter en cette minute ? Munis-toi vivement du coloris criard bien foncé .", category: "Funny", readTime: 2)
        ],
        "Grateful": [
            Story(title: "Le Pot de Remerciements", content: "Ah, quelle sensation infiniment enveloppante et démesurément réconfortante d'accéder à l'essence sublime qu’offre un vrai sursaut du cœur envers toutes nos fortunes! Ces vibrations apaisent vos artères et alevinent toutes poitrines lourdes du poids. Entend mon aveu intime au sujet de cette boîte magique : mon Boc de Verre Reconnaissant ! Vers le lit du soir, je prélevais furtivement de minces petits morceaux papiers dans le but exclusif rédiger l'apparition insignifiante des réjouissances qui marqua mon appréciation quotidienne . Au-delà quémander victoire des grosses loteries ou les luxueuses fortunes... le mot était “un abricot à la parfaite maturation ” ou l’effluve pétricor mouillant d’asphalte sous les ardeurs climatiques du soleil… Au dénouement semestriel; mon conteneur expulsait l'épaisse densité pleine de paperasserie . Modeler nos regards de la vie dans l’unique perception ciblant détecter de petits signes de beautés; fera basculer votre vie où ce ne se perçoivent qu'omniprésentes myriades célèbres du merveilleux .", category: "Moral", readTime: 3),
            Story(title: "Les Lunettes Dorées", content: "S'il vous plaît imagine durant un bref clignement que l'on vienne de vous remettre gracieusement la plus chic paire des lorgnettes féériques bordées toute recouvertes au précieux plaqué de jaune or resplendissant et immaculé ! . Dès leur position sur l’arc-arcade, de doux feux incandescents rayonnent le reflet brillant à tout le panorama visible qu’aime chèrement de tes choix intimes : Une tasse à la porcelaine au tiède arôme parfumé : éclat de lumière  ! Le fidèle épagneul canin : Un reflet irradiant au poil satin ! La baie fenêtre solaire rayonnant la verdure aux volets clairs : Encore Lueur pure. Posséder en conscience une humilité sincèrement remplie ne consistera à ne faire qu'ajouter vos montures optiques subtiles . Ainsi ton entourage t'empêchera avec miracle d'admirer tristement les éléments manquant non réalisés ;  mais tu plongeras dans un état béatement submergé et ravi de cette multitude radieuse d'éléments déjà tenus fortement contre ton berceau du présent actuel immédiat .", category: "Bedtime", readTime: 3),
            Story(title: "Le Cadeau d'Aujourd'hui", content: "Reste inscrite à mon cœur l’immense maxime indélébile traversant perpétuelle l'âme : le précédent est juste un temps dépassé révolu historique : Par la suite de tes pas ce sera toujours un mystère brouillé , Cependant l’Aujourd’hui vif et contemporain c'est bien la définition véritablement palpable du substantif “CADEAU-LE PRÉSENT”! Et figure-toi chérie chérissable ; tu te prêtes au jeu actuellement  à arracher le cordon papier-cadeau ouvrant de son ruban ce même cadeau ! Peu importent les secousses émotionnels inattendues féroces que les événements renferment. Toi tu seras délaissée en proie afin d'en épuiser de sa vitalité savoureuse en entier durant 24 longues majestueuses belles et bonnes et inestimables de précieuses et douces de formidables Heures !!!  Me tenant bénie du plaisir infini à ce doux partage où toi particulièrement s'es venu occuper ma petite personne le partage des précieuses millisecondes pour rester humble et s'émouvoir ensemble simplement au naturel !.", category: "Short", readTime: 1)
        ],
        "Excited": [
            Story(title: "Le Billet Pour N'importe Où", content: "Tiens-tiens !!  Mais ce serait presque visible  !! Cette vibration crépitante que  lancerait ton regard ! Tes étincelles vives évoquant très rapidement   un matin très lointain quand s'ouvrait  furtif par la boîte de courriers avec lettre : Un ticket de la ligne de TGV dissimulé inaperçu . Mon invitation ferroviaire de rejoindre tous terminus des lointaines l'éther et contrés paradisiaques! Connais – tu vraiment cette secousse stomacal abdominal en folie vibratoire effrénée ; cette envolée papillonnante s’avérant extrêmement aérienne de l’esprit ? Ce mouvement incarnerait les palpitations à vivre d’infinies frontalières portes illimitées! Empare toi fort fermement  ses  turbulences à dos d’un valeureux dragon ma grande téméraire, ce vent soutenu portera ton propre véhicule aux sphères lointaines . L'Univers s'immensise  grandiose et béant ; s’étalant en soupirant pour que très active : franchisses d’un bond d'allégresse le perron d'honneur ouvrant du jour nouveau .", category: "Short", readTime: 3),
            Story(title: "La Première Chute de Neige", content: "N’éprouves tu pas cette nostalgie saisissante en souvenance quand tu quittais aux petit-heure de tes doux drap d’enfant le réveil avec hâte le pas allant contre l'entrebâillement verrier ! . Et s’émerveillait par enchantement le regard vitrifié contemple cet incommensurable tapis majestueusement floconeux immaculé scintillait pure de clarté éblouissante. Cette soudaine bouffée irrépressible à s'en expulser directement contre ses poudres poudreuses fraîches  souhaitée être des premiers d’écraser son sceau à chaque marques piétinées puis par envie tirer sa petite langue aux flocons volant ! – Ceci serait le portrait fidèle symbolisant une fièvre juvénile . Agrippes solidement les sensibilités du petit-enfant intérieur : luit aux moindres découvertes étonnées au cœur des inédits évènements  !!.", category: "Nature", readTime: 2),
            Story(title: "L'Odeur de la Boulangerie", content: "Rien ne se révèlerait autant enivrant à tituber doucement les matins le long des ruelles  que sentir se propager l’effluve suave s'évaporant par la tourelle chauffantes aux coins de l’artisan boulangé !! Ces parfums dorés de pains d'épices en sucre filé, d’un nuage feuilletés de beurre riche te saisit des narines par ravissement  à te subjuguer un court interlude béatifique de salivement . Seule ta frémissante attente pénétrant par ce saint-lieu d’entamer ton  pionnier craquant croqué feuillu d’un croissant est d’un vertige addictif  qui étourdirait tout raisonnement ! Ahh .. Mon aimable . notre belle existence charrient en vrac ces abondants recoins  croustillant des surprises mielleuses espacés un peu partout attendant par la découverte un seul de nos regards !! Conserve dans ton cœur savouré tous ces intarissables émois extasiant une plénitude à pleines dents .", category: "Funny", readTime: 2)
        ]
    ]
}
